### ISSUE TITLE
Resque Web UI missing schedule tab when mounting inside Rails 4 routes

### ISSUE THREAD

**Issue by jrmehle** [resque/resque-scheduler#301]
In a Rails 4.0.2 app, mounting resque web in routes

``` ruby
mount ResqueWeb::Engine => "/resque_web"
```

I've tried requiring 'resque_scheduler', 'resque/scheduler', and 'resque_scheduler/server' just about everywhere I can think of (in an initializer on it's own, in config.ru, in application.rb) and I still can't get the Schedule or Delayed tabs to show up in Resque Web. The only way I've been able to see the tabs is if I throw those requires in a file and use the resque-web command to start the server. This is not a solution as I want to have resque web mounted within my app.

Is it possible to do this? Is there some other way to embed resque_web within Rails where this will work?

**Comment by mattgibson** [comment]
`gem 'resque-scheduler-web'` in your gemfile will fix this now, so that the schedule and delayed tabs show up in resque-web when you mount it.

All you need in `routes.rb` is

`mount ResqueWeb::Engine => "/resque_web"`

**Comment by gregmurray** [comment]
Got this working after following @bugant 's suggestion, thanks!

**Comment by jtmarmon** [comment]
@mattgibson's suggestion fixed it for me
