### ISSUE TITLE
Schedule loaded but jobs not enqueued

### ISSUE THREAD

**Issue by michele** [resque/resque-scheduler#409]
Hi,

I'm trying to get resque-scheduler to work on a new server (same app, same code, same everything was working on another server), however the schedule is correctly loaded (as per resque-web) but jobs aren't enqueued when they should.

No errors in the log:

```
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Loading Schedule
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Scheduling schedule-1 
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Scheduling schedule-2 
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Scheduling schedule-3 
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Scheduling schedule-4
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Scheduling schedule-5
resque-scheduler: [INFO] 2014-06-05T13:05:56+00:00: Schedules Loaded
```

Cron is specified without time-zone, so I'm considering the server's time which is UTC.

Thanks a lot for your help!

**Comment by kritiagg** [comment]
Hi, I am facing the same issue. Even after passing the DYNAMIC_SCHEDULE env variable, the jobs are not getting enqueued.

**Comment by naveen-furlenco** [comment]
Hey @kritiagg, I am facing the same issue. any help? the jobs are not getting enqueued. It is Stoping at `app/scheduler.1:  [INFO] 2016-05-24 12:29:44 +0000: Schedules Loaded`

**Comment by ibussieres** [comment]
Same issue. Also fine in development, but not in production.

**Comment by tp-clickapps** [comment]
@bugant 

We're facing the same issues with static as well as dynamic schedules on both dev and production. Is this having any dependency on redis-server's version?

**Comment by carsonreinke** [comment]
@tp-clickapps, what version of resque-scheduler?

**Comment by tp-clickapps** [comment]
@carsonreinke @bugant 

I got the problem resolved. Actually I've different servers in different time-zones. Specifying the timezone with the cron format resolved the issue like the following in schedule.yml :-

```
queue_users_for_calculation_of_eos_amount_monthly:
  cron: 50 12 1 * * <%= ENV['TZ_SERVER'] %>
  class: "CalculateEosAmountMonthlyWorker"
  queue: "monthly_eos_amount"
  description: "This job will update eos amount for employee every month"
```

Where **TZ_SERVER** variable in set as per server's timezone from the following list :-
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Also i did same for dynamic schedules too. So all the things are working as expected.

@kritiagg @neevany @ibussieres I guess this will work for you guys too.

**Comment by aivils** [comment]
This will solve case where job is running first time but never works as scheduled even it is enqueued correct.
I have Resque::Scheduler.dynamic = true
I had code like in resque-scheduler documentation:

```
  def schedule_source_import
    config = {}
    config[:class] = 'RSSImportJob'
    config[:args] = self
    config[:every] = ['1m', { first_in: 1.second }]
    config[:queue] = 'rss_import'
    config[:persist] = true
    Resque.set_schedule(schedule_name, config)
  end
```

After 1 day debuging I discover it does not work because it cannot handle directly RSSImportJob.
I changed my code to this one:

```
class ImportSource::RSS < ImportSource

  def schedule_source_import
    config = {}
    config[:class] = 'ImportSource::RSS::JobWrapper'
    config[:args] = self
    config[:every] = ['1m', { first_in: 1.second }]
    config[:queue] = 'rss_import'
    config[:persist] = true
    Resque.set_schedule(schedule_name, config)
  end

  class JobWrapper
    class << self
      def perform(job_data)
        RSSImportJob.perform_now(job_data)
      end
    end
  end
end
```
where class RSSImportJob < ActiveJob::Base
In ordinary way ActiveJob never pass Job to Resque queue but it pass ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper 
This wrapper do right job. My simple wrapper does same job.

Looks like resque-scheduler documentation is incomplete or obsolete at year 2017.

**Comment by darkknightsds** [comment]
@bugant When you say pass DYNAMIC_SCHEDULE env variable where are you passing it? https://github.com/resque/resque-scheduler/issues/409#issuecomment-45638418

**Comment by PoojaKarande** [comment]
@darkknightsds You pass with the command like this `DYNAMIC_SCHEDULE=true rake resque:work` and `DYNAMIC_SCHEDULE=true rake resque:scheduler`

**Comment by carsonreinke** [comment]
@darkknightsds @PoojaKarande This is an environment variable, you will need to use it when running the Rake task `resque:scheduler`.
