### ISSUE TITLE
README doesn't mention v3.0

### ISSUE THREAD

**Issue by mkenyon** [resque/resque-scheduler#428]
The opening table in the README still instructs users to install v2.x of the gem, even though v3.0.0 was released. The remaining documentation asks users to `require 'resque/scheduler/tasks'` when v2.x uses `require 'resque_scheduler/tasks'`.

Normally, I'd love to just submit a PR for a simple documentation tweak, but you already have a section explaining the changes when upgrading to v2, and I don't have enough context into resque-scheduler's changes to create a separate section for upgrading to v3.

**Comment by avecchio** [comment]
Could this issue be closed. It has been fixed.

**Comment by mkenyon** [comment]
Happy to close it! Thank you!
