### ISSUE TITLE
'Delete' button not working in Schedule tab of Resque-web

### ISSUE THREAD

**Issue by hpirosha** [resque/resque-scheduler#448]
When clicking on "Delete" button of a schedule, server landed on an error page showing message from sinatra app. The message indicated that server.rb has no implementation for post('/schedule') request.

Modified the server.rb and added the following line 

 post('/schedule') { delete_schedule }

restarted resque-web and the "Delete" button started to work. 

So, is this the right fix or I am missing something ?

**Comment by iscra** [comment]
The code and template seem to rely on the method override which should redirect post to delete routes.

You can add
  Rack::MethodOverride
to config.ru which handles this cases.

**Comment by proteantech** [comment]
@iscra Adding "use Rack::MethodOverride" worked. Thanks. Someone should do a pull request to modify the README to mention this and also I had to put the "Resque::Scheduler.dynamic = true" in the config.ru to get "Delete" to even show up.

**Comment by ciaoben** [comment]
Where exactly I need to put it?

**Comment by carsonreinke** [comment]
If you are using Rails, you don't.  If you using Sinatra, you can use add to config.ru the line `use Rack::MethodOverride`.  You need to have `Resque::Scheduler.dynamic` enabled for the Delete button to display and work.

**Comment by hpirosha** [comment]
It works now
