### ISSUE TITLE
Namespaced Job breaking "delayed" tab of resque web

### ISSUE THREAD

**Issue by kevbaldwyn** [resque/resque-scheduler#455]
Please don't hate on me for posting this! I have been using the php-resque port of resque and using resuqe-web and resque-scheduler with it. However when I "delay" a job with a php namespace (`Namespace\For\Job\Class`) it breaks the delayed tab with an error `URI::InvalidURIError at /delayed bad URI(is not URI?): /delayed/jobs/Namespace\Of\Job\Class?args=`. (It works fine with a job class that is not namespaced).

I appreciate this is probably not high priority or maybe not something you'd consider handling but it would be a great help to me and possibly a large number of people that use the excellent port of this excellent queue manager.

**Comment by carsonreinke** [comment]
You are using Ruby resque-web and resque-scheduler in combination with the PHP port of resque?

**Comment by kevbaldwyn** [comment]
Yes that's correct - I think it's the php namespace format for class names that is causing the issue.

**Comment by meatballhat** [comment]
@kevbaldwyn That's so cool!  For my part, I consider your discovery a bug in resque-scheduler.  Thanks for helping us find it!

**Comment by kevbaldwyn** [comment]
No problem!
