### ISSUE TITLE
delayed job keys not getting deleted

### ISSUE THREAD

**Issue by jblauer** [resque/resque-scheduler#491]
I'm processing a large number of jobs and running into OOM issues in Redis with maxmemory-policy set to volatile-lru.

Certain jobs depend on others, and so I'm using resque-scheduler to re-enqueue them for later, and doing this repeatedly until they are either processed or a certain amount of time has elapsed.

It seems that the delayed queue jobs, while they are eventually getting processed and disappearing from the delayed tab in resque-web, are never getting deleted. Eventually Redis runs out of memory and throws OOM errors.

I dumped the db with redis-dump and am analyzing it with grep. One job, for instance, that was retried 29 times, appears exactly 29 times in the keys array. So while they are getting enqueued, they don't seem to be getting deleted.

I'm assuming this is not normal behaviour, so any ideas why this is happening?

Using:
resque-scheduler (2.0.1)
resque (1.24.1)
redis (3.0.4)

**Comment by yaauie** [comment]
What specifically do the keys look like? What content to they hold? Feel free to scrub any sensitive data, but it's hard to chase down a leak (or a potential leak) without clues.

**Comment by jblauer** [comment]
Thanks Ryan, but I discovered the source of the problem.
