### ISSUE TITLE
Bump to 4.1.0 version

### ISSUE THREAD

**Issue by guizmaii** [resque/resque-scheduler#493]
There're some nice code additions. 

It could be great to move to v4.1.0 in order to continue to work on this code (and test with my personnal projects). 

No ?

**Comment by dominicsayers** [comment]
:+1:

**Comment by meatballhat** [comment]
Sorry for the big delay!  Addressing this is #510

**Comment by meatballhat** [comment]
:tada: finally

**Comment by guizmaii** [comment]
Thanks =)
