### ISSUE TITLE
resque (dynamic) scheduler  lost prevoius job after every restart

### ISSUE THREAD

**Issue by curbsaleem** [resque/resque-scheduler#494]
Hi 

I am using 'resque-scheduler', '~> 2.2.0' and 'resque', '1.24.1'. After every restart of resque-scheduler, i lost my all previously dynamically scheduled jobs. Do you know how we can overcome this problem.

Thanks

**Comment by carsonreinke** [comment]
How are you dynamically scheduling the job?  It looks like that if you used a combination of `schedule=` and `set_schedule` in 2.2.0, the use of `schedule=` would wipe anything pre-existing (see https://github.com/resque/resque-scheduler/blob/v2.2.0/lib/resque_scheduler.rb#L91).

**Comment by carsonreinke** [comment]
@curbsaleem still having issues?
