### ISSUE TITLE
resque-web has schedule and delayed tabs , delayed tabs shows delayed jobs but scheduled tab doesnt show 

### ISSUE THREAD

**Issue by tuhinjubcse** [resque/resque-scheduler#495]
I am using resque-scheduler
everything is working fine , jobs are scheduled as i run resque:schedule rake
they are worked upon as in run resque:work . so my functionality is achieved
now i wanted to see scheduled jobs in resque-web UI however i am having an issue

I have resque_config.rb in Rails root
contents

require 'resque-scheduler'
require 'resque'
require 'resque/scheduler/server'
Resque.redis = "localhost:6379"
Resque::Scheduler.dynamic = true

i do this
bundle exec resque-web -f -p 9292  ~/Documents/Promise-API/coms/resque_config.rb

where "/Documents/Promise-API/coms/" my Rails.root
but schedule jobs are still not shown . 

alternatively 
if i do 
Rails.application.routes.draw do
  mount Resque::Server.new, :at => '/resque'
end

 schedule jobs are still not shown , only delayed jobs . 

i need this a bit urgently 
Any help will be appreciated

**Comment by carsonreinke** [comment]
See https://github.com/resque/resque-scheduler/issues/541, you must also load the static schedule for the scheduler web to read since it is not persisted in Redis.
