### ISSUE TITLE
Resque.schedule = Resque.get_schedules under initializers giving error

### ISSUE THREAD

**Issue by curbsaleem** [resque/resque-scheduler#498]
gems/ruby-2.1.2@nut/gems/resque-scheduler-2.2.0/lib/resque_scheduler.rb:345:in `prepare_schedule': undefined method `each' for nil:NilClass (NoMethodError)
/.rvm/gems/ruby-2.1.2@nut/gems/resque-scheduler-2.2.0/lib/resque_scheduler.rb:52:in `schedule='
	from /app/Nutrition_api/config/initializers/resque.rb:20:in `<top (required)>

Any one know, how i can fix it?

Thanks

**Comment by carsonreinke** [comment]
As far I can tell, the only way to actually do this would be to set `Resque::Scheduler.schedule = nil`
