### ISSUE TITLE
Schedule tab does not reflect dynamic changes to schedule

### ISSUE THREAD

**Issue by genegc** [resque/resque-scheduler#501]
The 'Schedule' tab does not show changes that are dynamically made to the schedule.
If I restart resque-web, the changes appear.
This is on v4.0.0

**Comment by ch2ch3** [comment]
Hi @genegc, I had the same problem but managed to fix it by setting `Resque::Scheduler.dynamic = true` before I configured the web interface.

```ruby
# config.ru

require 'resque/server'
require 'resque-scheduler'
require 'resque/scheduler/server'
require_relative './app'

Resque.redis = 'my_redis:6379'
Resque::Scheduler.dynamic = true

use Rack::MethodOverride

run Rack::URLMap.new(
  '/'       => App,
  '/resque' => Resque::Server.new
)
```

**Comment by carsonreinke** [comment]
Yes, some sort of initializer for scheduler web must have the `Resque::Scheduler.dynamic = true`, otherwise the schedule is not read from Redis and only read from `Resque.schedule`.
