### ISSUE TITLE
Update README for Windows users regarding SIGUSR1

### ISSUE THREAD

**Issue by jchatel** [resque/resque-scheduler#502]
A note in the readme would be welcomed for Windows: http://stackoverflow.com/questions/34381171/resque-scheduler-unrecognized-signal-sigusr1

I ran into this as well.

**Comment by nicolasguenther** [comment]
I just run into this too. Does this mean resque-scheduler is totally incompatible with windows?

**Comment by meatballhat** [comment]
Closed via https://github.com/resque/resque-scheduler/pull/542
