### ISSUE TITLE
What about project future?

### ISSUE THREAD

**Issue by d4rk5eed** [resque/resque-scheduler#507]
Guys, I see some activity in resque repo, but here last commit was merged at may 2015.
Do you experiencing team problems?

**Comment by hassanakram** [comment]
+1

**Comment by dominicsayers** [comment]
:+1: Would be good to see some of the recent merges released

**Comment by avecchio** [comment]
It would be..

**Comment by avecchio** [comment]
It might be best to see if a fork can be made and updates made from that fork.

**Comment by meatballhat** [comment]
Hey everyone, this is a volunteer maintained project.  If you are
interested in becoming a maintainer, please say so in whatever pull
requests you have open.  Thanks for your patience.

**Comment by dominicsayers** [comment]
@meatballhat you are one of 3 owners of the gem on Rubygems. Just looking for a `gem build` and `gem release`. Happy to do this if you add me.

**Comment by meatballhat** [comment]
@dominicsayers the release process is a bit different than that, but I catch your drift.  I'm getting a release prep branch ready now :+1:

**Comment by dominicsayers** [comment]
:shipit:

**Comment by meatballhat** [comment]
Awaiting the green :smiley_cat: https://github.com/resque/resque-scheduler/pull/510

**Comment by carsonreinke** [comment]
@meatballhat would love the ability to close some of these issues for this project.

**Comment by meatballhat** [comment]
@carsonreinke Help is much appreciated!
