### ISSUE TITLE
Dynamic schedule "persist" option does not work

### ISSUE THREAD

**Issue by ygnessin** [resque/resque-scheduler#530]
It appears the `persist` flag is broken:

```ruby
> Resque.set_schedule('my_job', class: MyJob, every: '10m', persist: true)
=> {:class=>MyJob, :every=>"10m"}
> REDIS.sismember(:persisted_schedules, 'my_job')
=> false
```

A fix for this would be much appreciated, this bug just caused my team a lot of pain. In the meantime, I think I can get around it by running this:

```ruby
> REDIS.sadd(:persisted_schedules, 'my_job')
=> true
```

**Comment by carsonreinke** [comment]
I see this as working with 4.1.0, what version of the gem are you using?

**Comment by ygnessin** [comment]
@carsonreinke thanks for responding, I am on 4.0.0.

However, I realized a few days ago that possibly `persist` is actually working as intended and I misunderstood what it's for - I thought that if the schedule is set to "every 10 minutes" and I restart 6 minutes after the last job ran, the next job will run again in 4 minutes, rather than resetting to 0 and running again in 10 minutes, which is what I observed and tried to debug when I came across the code sample above.

Is this how it's supposed to work? If this is intended behavior, then I'll close this issue. For what it's worth, I've already worked around the problem by scheduling my jobs with `cron` instead of with `every`.

Thank you!

**Comment by carsonreinke** [comment]
@ygnessin I think that is how everybody wants it to work, but it works like what you have observed, since this is how rufus works.  The `persist` option just persists the dynamic scheduling of that job even when the scheduler daemon is not running.

**Comment by ygnessin** [comment]
@carsonreinke thanks for clarifying for me, I'll go ahead and close this issue. If anyone comes across this in the future, I recommend working around the problem using `cron` scheduling.
