### ISSUE TITLE
resque-scheduler process gets killed automatically

### ISSUE THREAD

**Issue by anmolarora** [resque/resque-scheduler#533]
resque-scheduler process gets killed automatically by my VM. Is somebody facing the same issue?

**Comment by hkdsun** [comment]
Can you give more details? A PR was just merged that fixes the bootup issue on latest master: https://github.com/resque/resque-scheduler/pull/532

**Comment by anmolarora** [comment]
I'll try again if the problem still persists. I'll get back to you.
