### ISSUE TITLE
we are noticing lag in delayed job scheduling

### ISSUE THREAD

**Issue by taf2** [resque/resque-scheduler#540]
e.g. jobs schedule via Resque.enqueue_in(x.seconds, ...

We are noticing that the schedulers are not able to keep up.   Any suggestions for debugging a lag in when jobs are queued?

**Comment by carsonreinke** [comment]
What does the resque-scheduler output say?  Turning on VERBOSE and checking what you have configured for RESQUE_SCHEDULER_INTERVAL will help.

**Comment by taf2** [comment]
We bounced everything and flushed the master lock and restarted all the schedulers... things caught up pretty quickly...  I'll keep an eye out for if this happens again.

**Comment by hkdsun** [comment]
Just out of curiosity, how many jobs did you have scheduled or in your delayed queue?

I'm gonna close this and you can re-open if the issue happens again.

**Comment by taf2** [comment]
we have thousands scheduled any given period of time... normally it's rock solid so i think it might just be a matter of we had not bounced the scheduler in quiet a long time or maybe a network blimp between one of our redis servers and the scheduler... looking good this morning.
