### ISSUE TITLE
Logging quiet when backgrounded even when logfile is set

### ISSUE THREAD

**Issue by xeron** [resque/resque-scheduler#565]
Resque log is always empty after some recent updates. May be related to https://github.com/resque/resque-scheduler/pull/559

I use `resque-scheduler` and `capistrano-resque`. Parts of my configuration:

_resque.rake_:

``` ruby
  task :setup_schedule => :setup do
    ENV['VERBOSE'] = '1'
    ENV['QUIET'] = nil
    ENV['LOGFILE'] = Rails.root.join("log", "resque-scheduler.log").to_s
```

_deploy.rb_

``` ruby
set :resque_verbose, true
set :resque_extra_env, "VERBOSE=1"
```

So I tried to enable `VERBOSE` even in different places and it still doesn't work.

This is how capistrano starts scheduler:

```
$ cap production resque:scheduler:start
00:00 resque:scheduler:start
      01 nohup bundle exec rake RAILS_ENV=production PIDFILE=/…/shared/tmp/pids/scheduler.pid BACKGROUND=yes VERBOSE=1 MUTE=1 resque:scheduler >> /dev/null 2>> /dev/null
```

**Comment by meatballhat** [comment]
What is setting `MUTE=1`?

**Comment by meatballhat** [comment]
Well... `MUTE` may not be related 😸  What version of `resque-scheduler` are you using?

**Comment by xeron** [comment]
@meatballhat I use `4.3.0`.

`MUTE` is from https://github.com/sshingler/capistrano-resque/pull/47 but it's probably not related at all. Log file started to be empty only recently and I believe it's because of https://github.com/resque/resque-scheduler/pull/559.

**Comment by meatballhat** [comment]
@xeron Ah!  Now I see.  Thanks!

**Comment by VipulSarin** [comment]
If your using the CLI and backgrounding it, a workaround for now is to set 
```ruby
Resque::Scheduler.logger.level = 0
```
in an initializer file. This resets the logging level back to DEBUG from FATAL=4.
