### ISSUE TITLE
Dynamic schedule can't be updated

### ISSUE THREAD

**Issue by lhf-leo** [resque/resque-scheduler#570]
I'm having problem when I update a dynamic schedule. 
For instance, at 1:00 pm I set a schedule for 1:05. Then, before 1:05, I change the schedule by remove_schedule and set_schedule to 1:10.
The job will still be triggered at 1:05.
Any suggestion?

**Comment by lhf-leo** [comment]
Just found #369.
`Resque::Scheduler.dynamic = true` is not working, use `DYNAMIC_SCHEDULE=true`.

**Comment by carsonreinke** [comment]
@lhf-leo What version of the gem are you using?

**Comment by lhf-leo** [comment]
@carsonreinke It's 2.5.5

**Comment by greatavi79** [comment]
Hi, the dynamic schedules are not working with me even with latest versions. I have tried using both options i.e. Resque::Scheduler.dynamic = true and DYNAMIC_SCHEDULE=true. Please help.
