### ISSUE TITLE
dynamic resque schedule changes do not get picked up by scheduler

### ISSUE THREAD

**Issue by greatavi79** [resque/resque-scheduler#571]
The dynamic schedules do not work even on providing Resque::Scheduler.dynamic = true and DYNAMIC_SCHEDULE=true.
The schedules do get updated on resque-web but the schedule changes do not get picked up by the scheduler. For ex, the removed schedules no longer appear on resque-web but they still get run by scheduler.
The setup is as follows:
(A) Redis: Deployed in a docker container. 
Redis server version:  2.8.4

(B) Resque: Deployed in another docker container started with a link to redis server (--link redis:db). This container also contains resque-scheduler and resque-pool.
resque version: 1.26.0
resque-pool version:  0.6.0
resque-scheduler version: 4.3.0
rufus-scheduler version: 3.2.1

(C) resque.rb (in Resque container web-app's config/initializers):
---
require "redis"
require 'resque-scheduler'
require 'resque/scheduler/server'

REDIS_SERVER = Redis.new(:host => ENV["DB_PORT_6379_TCP_ADDR"], :port =>  ENV["DB_PORT_6379_TCP_PORT"])
Resque.redis = REDIS_SERVER

Resque::Scheduler.dynamic = true
Resque.schedule = YAML.load_file('resque_schedule.yml')
---

(D) resque.rake (in Resque container web-app's lib/tasks)
---
require "resque/tasks"
require 'resque/pool/tasks'
require 'resque/scheduler/tasks'
require "redis"
require 'resque-scheduler'
require 'resque/scheduler/server'

namespace :resque do
  task :setup => :environment do
    require 'resque'

    Resque.redis = REDIS_SERVER
  end

  task :setup_schedule => :setup do
    require 'resque-scheduler'

    Resque::Scheduler.dynamic = true
  end

  task :scheduler => :setup_schedule

  task "pool:setup" do
    ActiveRecord::Base.connection.disconnect!
    Resque::Pool.after_prefork do |job|
      ActiveRecord::Base.establish_connection
      Resque.redis.client.reconnect
    end
  end

end
---

(E) Within resque container:
(a) The resque workers are started using:
resque-pool --daemon --environment production
(b) The resque scheduler is started using:
rake environment resque:scheduler DYNAMIC_SCHEDULE=true

(F) On the fly, the resque schedules are updated using Resque.set_schedule and Resque.remove_schedule methods.

**Comment by carsonreinke** [comment]
What does `resque:scheduler` daemon output when running?

**Comment by greatavi79** [comment]
resque:scheduler daemon says 'updating schedule, schedules loaded' when scheduled is updated from set_schedule method. Here is the output:
---
root@4ec141e42cb4:/usr/src/app# resque-pool --daemon --environment production
root@4ec141e42cb4:/usr/src/app# rake environment resque:scheduler DYNAMIC_SCHEDULE=true
/usr/local/bundle/gems/activesupport-4.0.4/lib/active_support/values/time_zone.rb:283: warning: circular argument reference - now
/usr/local/bundle/gems/activerecord-4.0.4/lib/active_record/associations/has_many_association.rb:76: warning: circular argument reference - reflection
/usr/local/bundle/gems/activerecord-4.0.4/lib/active_record/associations/has_many_association.rb:80: warning: circular argument reference - reflection
/usr/local/bundle/gems/activerecord-4.0.4/lib/active_record/associations/has_many_association.rb:84: warning: circular argument reference - reflection
/usr/local/bundle/gems/activerecord-4.0.4/lib/active_record/associations/has_many_association.rb:103: warning: circular argument reference - reflection
RAILS_ENV:production
resque-scheduler: [INFO] 2016-08-01T20:29:09+00:00: Starting
resque-scheduler: [INFO] 2016-08-01T20:29:09+00:00: Reloading Schedule
resque-scheduler: [INFO] 2016-08-01T20:29:09+00:00: Loading Schedule
resque-scheduler: [INFO] 2016-08-01T20:29:09+00:00: Scheduling dev2_ReleaseWorker
resque-scheduler: [INFO] 2016-08-01T20:29:10+00:00: Schedules Loaded
resque-scheduler: [INFO] 2016-08-01T20:30:00+00:00: queueing ReleaseWorker (dev2_ReleaseWorker)
resque-scheduler: [INFO] 2016-08-01T20:31:30+00:00: Updating schedule
resque-scheduler: [INFO] 2016-08-01T20:31:30+00:00: Schedules Loaded
---

The newly set schedule is available on resque-web but never gets picked up by scheduler. Please find attached images.
![after_adding](https://cloud.githubusercontent.com/assets/20730609/17308066/06c8d09c-5806-11e6-8ad2-a01859f1261f.png)
![before_adding](https://cloud.githubusercontent.com/assets/20730609/17308065/06bc2c8e-5806-11e6-9e22-816fd60e4eda.png)

**Comment by greatavi79** [comment]
@carsonreinke can you please provide your feedback.

**Comment by carsonreinke** [comment]
Is `dev2_ReleaseWorker` loaded from `YAML.load_file('resque_schedule.yml')`?  Could you provide the snippet from `rails console` of how you are scheduling `dev4_ReleaseWorker`?

**Comment by carsonreinke** [comment]
I'm wondering if setting `Resque.redis` twice in Rake task and the initializer is causing some sort of problem.  Since the `environment` task will run the initializer.

**Comment by greatavi79** [comment]
@carsonreinke yes dev2_ReleaseWorker is loaded from load_file. dev4_ReleaseWorker is scheduled using:
Resque.set_schedule(env.name + "_" + @@module_worker_map[mod_type], generate_schedule(env, mod))

where generate_schedule is:
def self.generate_schedule(env, mod)
    schedule_map = Hash.new
    args = Array.new
    schedule_map.store("cron", mod.schedule)
    schedule_map.store("class", @@module_worker_map[mod.mod_type])
    args.push(mod.env_id.to_s)
    args.push(mod.id.to_s)
    schedule_map.store("queue", @@worker_queue_map[@@module_worker_map[mod.mod_type]])
    schedule_map.store("args", args)
    schedule_map.store("description", "This job queues " + @@module_worker_map[mod.mod_type] + " on " + env.name)
    return schedule_map
  end

I had tried setting Resque.redis only once as well (only in resque.rb), but same behavior.

**Comment by carsonreinke** [comment]
Try including `:persist => true` within `schedule_map`.

**Comment by greatavi79** [comment]
@carsonreinke persist=true worked:

resque-scheduler: [INFO] 2016-08-02T19:02:46+00:00: Starting
resque-scheduler: [INFO] 2016-08-02T19:02:46+00:00: Reloading Schedule
resque-scheduler: [INFO] 2016-08-02T19:02:46+00:00: Loading Schedule
resque-scheduler: [INFO] 2016-08-02T19:02:46+00:00: Scheduling dev2_ReleaseWorker
resque-scheduler: [INFO] 2016-08-02T19:02:47+00:00: Schedules Loaded
resque-scheduler: [INFO] 2016-08-02T19:03:37+00:00: Updating schedule
resque-scheduler: [INFO] 2016-08-02T19:03:37+00:00: Scheduling dev4_ReleaseWorker
resque-scheduler: [INFO] 2016-08-02T19:03:37+00:00: Schedules Loaded
resque-scheduler: [INFO] 2016-08-02T19:05:00+00:00: queueing ReleaseWorker (dev2_ReleaseWorker)
resque-scheduler: [INFO] 2016-08-02T19:08:00+00:00: queueing ReleaseWorker (dev4_ReleaseWorker)

I had been trying to make this work from quite a while and good that as last resort, i asked for help here. Thank you Carson.
However, the documentation is not very clear on persist. I thought that it meant that scheduler restarts will persist the schedules instead of meaning that scheduler wont even need to be restarted for any dynamic schedule changes.
Is my understanding now correct that DYNAMIC_SCHEDULE will only work if persist is true?

**Comment by carsonreinke** [comment]
Yes, you need the `DYNAMIC_SCHEDULE` environment variable to be on.

Personally, I think it would be a lot easier if by default `Resque::Scheduler.dynamic = true` and `:persist => true`.  The documentation is definitely a big complaint.
