### ISSUE TITLE
Clarification of "Deployment Notes" section of the readme

### ISSUE THREAD

**Issue by joshuacronemeyer** [resque/resque-scheduler#572]
Hi,

I'm a little confused by the following from the deployment notes section of the readme:

> It is recommended that a production deployment of resque-scheduler be hosted on a dedicated Redis database. While making and managing scheduled tasks, resque-scheduler currently scans the entire Redis keyspace, which may cause latency and stability issues if resque-scheduler is hosted on a Redis instance storing a large number of keys (such as those written by a different system hosted on the same Redis instance).

It sounds like you're recommending a separate redis DB instance just for scheduler, but reading the code it seems you need to have a separate DB for ALL of Resque.

Let me know if what I'm saying is correct and I'll submit a pull request that updates the language in this section of the readme to be a bit clearer.

**Comment by carsonreinke** [comment]
You are correct, you don't need an entire Resque instance for resque-scheduler, instead a Redis DB instance will work.
