### ISSUE TITLE
 Scheduled jobs not shown under Schedule tab in 4.3.0

### ISSUE THREAD

**Issue by malakai97** [resque/resque-scheduler#573]
Simiilar behavior to #541, except this is the first time I've set this up.

`bundle exec rake resque:scheduler` launches as you'd expect and tells me that the job has been scheduled.  I can see the tabs in the web view, I just don't see any jobs.

It seems like this line in the documentation is not true:

> As of resque-scheduler 2.0.0, it's no longer necessary to have the resque-web process aware of the schedule because it reads it from redis.

```
Using resque 1.26.0
Using resque-pool 0.6.0
Using resque-scheduler 4.3.0
```

**Comment by carsonreinke** [comment]
> don't see any jobs

Could you clarify on what you mean?  Do you see any jobs in the Schedule tab?

**Comment by carsonreinke** [comment]
You are going to have to load a static schedule and/or set `Resque::Scheduler.dynamic` in an initializer for `resque-web`.

So, the simplest would be an initializer like this:

```ruby
Resque::Scheduler.dynamic = true #If using dynamic schedule
Resque.schedule = YAML.load_file ... #If using static schedule
```

Hopefully that will work.

**Comment by malakai97** [comment]
> As of resque-scheduler 2.0.0, it's no longer necessary to have the resque-web process aware of the schedule because it reads it from redis.

Loading the schedule statically works, but the point of this issue is that the documentation above says that resque-web will read the schedule from redis, but it does not.  Setting dynamic = true in a rails initializer did not work.

There might just be a problem with the way I'm understanding the quoted documentation.  Could you point me to where in the code the quoted functionality exists?  This way I'll be able to check my understanding and--if necessary--submit a patch to clarify the documentation.

**Comment by jconley88** [comment]
@malakai97, you likely have the same issue as #541 as it's with the new version itself and not a specific upgrade path.  The store for non-persisted schedules was recently changed from redis to in-memory.   Resque web has no way to access the actual schedules unless you load them separately in each process.  If you're not using dynamic schedules, it's probably not that big of a deal.  You can load the static schedule twice and they're unlikely to differ. If you are, you might be able to set all of your jobs to persist since this should use redis as storage.

One caveat with that is that it has to be done on an individual schedule level.  The other is that you can't remove a job from your resque_schedule.yml and expect it to be removed from the scheduler process when it's restarted.  It will persist until you dynamically delete it.

We were using a combination of static schedules to initialize the system and dynamic so that we could modify them on the fly.  The new dynamic in-memory store makes the UI misleading though.  I opted to forgo the dynamic option, revert to pure static scheduling and deal with requiring a deploy to change our schedules.

I think more thought needs to go into the design of dynamic schedules so we can have a functioning UI again.  Static schedules can be in-memory, but dynamic should be stored in redis and always persisted.  I also think the dynamic and static options should be made mutually exclusive to simplify behavior at restart:  Dynamic changes always persist and static files are always reloaded.

**Comment by yihoyoung** [comment]
Hi, I have same problems, with using resque-scheduler.

**Comment by yihoyoung** [comment]
Use resque-scheduler 4.1.0
Use rufu-scheduler 1.3.0  (on dependency, see Gemfile.lock)
Then dynamic schedule work well.

**Comment by carsonreinke** [comment]
@yihoyoung I believe this will depend on weather the the scheduler daemon is running for dynamic jobs or not.

**Comment by jconley88** [comment]
@carsonreinke, I think this is still an issue.  @yihoyoung's solution was to downgrade resque scheduler to 4.1.0.  4.2 seems to have broken the schedule tab in resque-web.  Is there a known solution for the current version?

**Comment by carsonreinke** [comment]
Sorry, I was under the impression that @malakai97 problem was resolved and this was more of side note.

@yihoyoung, were you having an issue even after the stated resolution above?

**Comment by yihoyoung** [comment]
@carsonreinke  I will monitor if resque-schedule works well after downgrade to 4.1.0. 
Yesterday, resque-schedule works well. but I need to monitor more.

**Comment by yihoyoung** [comment]
I don't understand why my dynamic resque-schdule just works one time that invokes http request.

**Comment by carsonreinke** [comment]
@yihoyoung, you are saying that the dynamic schedule only works after going to `resque-web`?  Is your dynamic schedule setup in an initializer or something?

**Comment by yihoyoung** [comment]
@carsonreinke I mean the dynamic schedule just works one time. I was dynamic schedule setup in an initializer file.
when I test simple job that has short response time, dynamic schedule works well.
but when I test complex job that has long response time, dynamic schedule just works one time, and resque-schedule process died after few days.

**Comment by carsonreinke** [comment]
@yihoyoung, could you put in a new issue with problem you are having as that is not related `resque-web`.  There is no reason why a long running job should crash `resque-scheduler` daemon nor prevent it from scheduling the job again.

Any additional information about versions and your setup would be very helpful.

**Comment by yihoyoung** [comment]
@carsonreinke I thank this is still a issue.  I'm so sorry for being confusing. In version 4.3 dynamic jobs still didn't show in Schedules tab. So I just tried at version 4.1.

**Comment by carsonreinke** [comment]
Could you provide your configuration (e.g. initializers) and how you were adding the dynamic schedule under 4.3?  Hopefully we can get to the bottom of this.

For the other issue you mentioned, could you enter a new issue?

**Comment by malakai97** [comment]
@carsonreinke Sorry, I have been busy and could no read through this until now.  I believe @yihoyoung has a different issue than me.

My issue is not resolved; I'm actually not sure which workaround/fix/instruction I should have applied that might have resolved it.  

@jconley88 seems to have confirmed the existence of my issue; he certainly appears more knowledgeable on the topic.  

I should have more time to examine #541 later, but from the first post it does seem that this issue is a duplicate--that may indicate that the issue is not fixed at this time.

**Comment by carsonreinke** [comment]
@malakai97 could you possibly post more information about your configuration and setup?  I re-opened, as definitely want to get resolved.  https://github.com/resque/resque-scheduler/issues/541 did uncover issues, besides lack of clear documentation.

I also setup a sample Rails setup to show a possible simple configuration: https://github.com/carsonreinke/resque-scheduler-sample (there is also probably more optimal ways to set this up).  Maybe that could help demonstrate a working setup, maybe not, I hope it will.

**Comment by malakai97** [comment]
I have setup a minimal rails application using resque-scheduler that exhibits the erroneous behavior. It can be found [here.](https://github.com/malakai97/resque-scheduler-bug)  Hopefully that provides all the information necessary without extra clutter.

**Comment by carsonreinke** [comment]
@malakai97 and I gave you a PR 😉 

Basically https://github.com/carsonreinke/resque-scheduler-bug/commit/587b21d32174929f2a43247b7126399a449f8732 just moves the loading of the static schedule to initializer so it can be made available to `resque-web`.  If you are using a dynamic schedule also, well you don't need to do that.

**Comment by malakai97** [comment]
This brings us back to the original point of this issue: the documentation from(quoted below) is not true.

> As of resque-scheduler 2.0.0, it's no longer necessary to have the resque-web process aware of the schedule because it reads it from redis.

Now, obviously, I'd love for it to be true, but I understand that the text is two major versions behind the project, the code comes first, etc.

Do you agree with this assessment?  If so, I can submit a PR that updates the documentation.

**Comment by malakai97** [comment]
Your change resolves the problem in my app (thanks!), but given that this issue was about the documentation I have a couple questions:

What is actually happening here?  Specifically:

1. Where is the rails initializer loading the schedule?  
2. Where is the resque-web schedule tab reading the schedule from? 
3. Where is the resque-scheduler process (started with rake resque:scheduler) reading the 
    schedule from? 

Sorry to make you type up a small novel over the course of this issue.

**Comment by carsonreinke** [comment]
I can't really say about the documentation, maybe that was suppose to be regarding dynamic schedules, not sure though.  When you use static schedule it definitely does not store it anywhere (see https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/scheduling_extensions.rb#L85).  Maybe providing `:persist` for a static schedule works and what the doc was referring to.

1. The rails initializer `resque.rb` gets loaded when Rails boots up automatically, this loads a static schedule.
2. `resque-web` is loaded within Rails, so the initializer gets called and loads the schedule making it available to display.
3. Same as #2, the Rake task depends on Rails `:environment` task which loads the Rails environment.

**Comment by carsonreinke** [comment]
@malakai97, do you have it working now?

https://github.com/resque/resque-scheduler/pull/580

**Comment by malakai97** [comment]
The change you proposed resolved my issue.  This PR seems to address the misleading documentation.  I suggest merging #580 and closing this.

**Comment by nextofsearch** [comment]
Hi,

I have 2 rails_app: Rails#1 for dashboard with resque-web-ui (Ruby 1.9.3, Rails 3.2.22.5, resque-scheduler 4.1.0) and Rails#2 for resque workers (Ruby 1.9.3, Rails 3.1.12, resque-scheduler 4.3.0). A scheduler loads schedules and works just fine without any problem. But I don't see any jobs in scheduled tab in web-ui. What should I do to fix this? Do I need to load the same schedule file in Rails#1 which I use in Rails#2?

FYI, upgrading Rails or resque-scheduler on Rails#2 is not an option.

**Comment by nextofsearch** [comment]
I made all the schedules persistent using YAML but make no difference.

**Comment by carsonreinke** [comment]
@nextofsearch if you don't mind, could you put in a separate issue for this as it sounds like a different issue.

It sounds like resque-scheduler 4.1 and 4.3 probably would not be compatible together, to start with see https://github.com/resque/resque-scheduler/issues/563.

**Comment by nextofsearch** [comment]
@carsonreinke got it. thanks.
