### ISSUE TITLE
Scheduler tab in Web console and Redis does not show schedule

### ISSUE THREAD

**Issue by astudnev** [resque/resque-scheduler#582]
I recently updated from resque-scheduler (4.0.0) to the following configuration:

    resque-scheduler (4.3.0)
      mono_logger (~> 1.0)
      redis (~> 3.3)
      resque (~> 1.26)
      rufus-scheduler (~> 3.2)

everything works fine, but now i have empty list of schedules in Web UI.

Also Redis does not show keys for schedule:

127.0.0.1:6379[1]> keys *sch*
1) "resque:resque:resque_scheduler_master_lock"

Start script is:

studnev@leadads:/var/www/leadada-tracker/current$ cat lib/tasks/resque.rake 
# Resque tasks
require 'resque/tasks'
require 'resque/scheduler/tasks'

namespace :resque do

  task :setup => :environment do
    require 'resque'
  end

  task :setup_schedule => :setup do
    require 'resque-scheduler'
    Resque::Scheduler.dynamic = true
    Resque.schedule = YAML.load_file('config/resque_schedule.yml')
  end

  task :scheduler => :setup_schedule
end

(the line Resque::Scheduler.dynamic = true was added later, but wth 4.0 it worked without this line )

Scheduler itself works just fine, this is output from start log:

resque-scheduler: [INFO] 2016-09-20T14:02:52+03:00: Starting
resque-scheduler: [INFO] 2016-09-20T14:02:52+03:00: Reloading Schedule
resque-scheduler: [INFO] 2016-09-20T14:02:52+03:00: Loading Schedule
resque-scheduler: [INFO] 2016-09-20T14:02:52+03:00: Scheduling leads_conversion_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:52+03:00: Scheduling leadada_monitor_unprocessed_worker 
resque-scheduler: [INFO] 2016-09-20T14:02:53+03:00: Scheduling leadada_info_update_job 
resque-scheduler: [INFO] 2016-09-20T14:02:53+03:00: Scheduling cpahub_conversion_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:53+03:00: Scheduling cpahub_conversion_pre_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:53+03:00: Scheduling etl_log_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:54+03:00: Scheduling etl_log_writer 
resque-scheduler: [INFO] 2016-09-20T14:02:54+03:00: Scheduling publisher_postback_sender 
resque-scheduler: [INFO] 2016-09-20T14:02:54+03:00: Scheduling leadsale_conversion_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:54+03:00: Scheduling cbki_conversion_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:55+03:00: Scheduling aleshop_sale_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:55+03:00: Scheduling protein_company_sale_reader 
resque-scheduler: [INFO] 2016-09-20T14:02:55+03:00: Schedules Loaded
resque-scheduler: [INFO] 2016-09-20T14:03:09+03:00: queueing etl_log_writer (etl_log_writer)
resque-scheduler: [INFO] 2016-09-20T14:03:24+03:00: queueing publisher_postback_sender (publisher_postback_sender)
resque-scheduler: [INFO] 2016-09-20T14:05:00+03:00: queueing leadada_info_update_job (leadada_info_update_job)
resque-scheduler: [INFO] 2016-09-20T14:05:09+03:00: queueing etl_log_writer (etl_log_writer)
resque-scheduler: [INFO] 2016-09-20T14:05:24+03:00: queueing publisher_postback_sender (publisher_postback_sender)
resque-scheduler: [INFO] 2016-09-20T14:07:09+03:00: queueing etl_log_writer (etl_log_writer)
resque-scheduler: [INFO] 2016-09-20T14:07:24+03:00: queueing publisher_postback_sender (publisher_postback_sender)
resque-scheduler: [INFO] 2016-09-20T14:09:00+03:00: Updating schedule
resque-scheduler: [INFO] 2016-09-20T14:09:00+03:00: Scheduling leads_conversion_reader

**Comment by carsonreinke** [comment]
resque-web needs to be aware of your schedule via `Resque.schedule`, most likely using an initializer.  You don't need to use `Resque::Scheduler.dynamic = true` unless you are dynamically scheduling.  See https://github.com/resque/resque-scheduler/pull/580 and https://github.com/resque/resque-scheduler/issues/573

**Comment by astudnev** [comment]
#580 really explains it, but then i do not understand how Web console may exchange data with task running scheduler.
Also in Rails environment it is now unclear where to put the Resque configuration - any recommendations ?

**Comment by carsonreinke** [comment]
@astudnev resque-web exchanges data with scheduler using Redis.  Non-dynamic schedules are not shared via Redis, resque-web just will need to be aware of that via `Resque.schedule`.

You could do something like this: https://github.com/carsonreinke/resque-scheduler-sample/blob/master/config/initializers/resque.rb

**Comment by astudnev** [comment]
Got it, and this solved my problem

However, it looks strange, that the client should load the server configuration in order to display.

**Comment by amorimlucas** [comment]
@carsonreinke Is there something similar I can do for delayed jobs? They aren't showing on resque-web for me. How can I persist them to redis?
