### ISSUE TITLE
Can't schedule static tasks

### ISSUE THREAD

**Issue by fergusom** [resque/resque-scheduler#583]
I am having this same problem: https://github.com/resque/resque-scheduler/issues/115

but the solution doesn't work because I am not using dynamic scheduling.

In my lib/tasks/resque.rake file I have:

```
require 'resque/tasks'

task "resque:setup" => :environment do
  ENV['QUEUE'] = '*'
end

task :setup_schedule => :setup do
  require 'resque-scheduler'
  Resque.schedule = YAML.load_file('#{Rails.root}/config/static_schedule.yml')
  require 'jobs'
end
task :scheduler => :setup_schedule

desc "Alias for resque:work (To run workers on Heroku)"
task "jobs:work" => "resque:work"
```

And in static_schedule.yml I have:

```

---
FixSchedulesJob:
  description: 'clear verification codes'
  queue: scheduled
  class: ScheduledTasks
  every: '30s'
```

but whenever I run the setup, I see:

```
[INFO] 2016-09-21 05:02:20 +0000: Loading Schedule
[INFO] 2016-09-21 05:02:20 +0000: Schedule empty! Set Resque.schedule
[INFO] 2016-09-21 05:02:20 +0000: Schedules Loaded
```

why isn't the schedule being loaded?

**Comment by carsonreinke** [comment]
@fergusom I think you are simply missing the `namespace :resque` around your defined Rake tasks (`:setup_schedule` and `:scheduler`)

**Comment by fergusom** [comment]
Ok, after adding the namespace wrapper I get the error: `LoadError: cannot load such file -- resque-scheduler`

My Rakefile btw looks like this:

```
require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

require 'resque/tasks'
require 'resque_scheduler/tasks'
```

**Comment by carsonreinke** [comment]
You don't need these lines if running from Rails:

```
require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
```

You will want the `resque:setup` task to require the Rails environment by doing `task :setup => :environment`.

I'm sure there is other ways to do this.

**Comment by fergusom** [comment]
I think I'm already doing that? My setup task looks like this:

```
task "resque:setup" => :environment do
  ENV['QUEUE'] = '*'
end
```

**Comment by carsonreinke** [comment]
Oh yes, sorry.

What version of resque-scheduler are you using?  The current doc says to `require 'resque/scheduler/tasks'`, but you are using `require 'resque_scheduler/tasks'`, which makes me think you are using an older version and probably why `require 'resque-scheduler'` would be missing.

**Comment by fergusom** [comment]
I think the newest version because I just put `gem 'resque-scheduler'` in my Gemfile

I found the `requre 'resque_scheduler/tasks` in the example app. I used it instead of `resque/scheduler/tasks` because when I add that line I get this error when compiling: `LoadError: cannot load such file -- resque/scheduler/tasks`

**Comment by carsonreinke** [comment]
Check your `Gemfile.lock` to see what version of `resque-scheduler` you are using.  You might be using 2.* instead of the latest of 4.*.

**Comment by fergusom** [comment]
oh yea its using `2.2.0`. Should I update my Gemfile to: `gem 'resque-scheduler' '4.3.0'`?

**Comment by carsonreinke** [comment]
@fergusom You would need to run another Rake task for the resque worker(s), as resque-scheduler does not spawn those, it only takes the scheduled job and puts it in the queue for resque.

**Comment by fergusom** [comment]
Ok ignoring the controller, shouldn't I be seeing `Running scheduled` in my server logs?

I based this task on the example app where the schedule is:

```
---
FixSchedulesJob:
  description: 'Add any missing email sending schedules'
  queue: send_emails
  every:
    - '1h'
    - :first_in: '10s'
```

and the job is:
```
class SendEmailJob
  @queue = :send_emails

  def self.perform(_user_id)
    # ... do whatever you have to do to send an email to the user
  end

```

If a separate rake task is needed to initiate the enquened jobs, is there a way to schedule those rake tasks? How can they run automatically?

**Comment by fergusom** [comment]
Ok I started a resque worker before running the scheduler

`TERM_CHILD=1 QUEUES=* rake resque:work --trace`

and I see in the console:

```
** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute resque:setup
** Execute resque:preload
** Invoke resque:setup
** Execute resque:work 
```

then I ran the resque scheduler and saw:

```
resque-scheduler: [INFO] 2016-09-22T22:15:41+00:00: Starting
resque-scheduler: [INFO] 2016-09-22T22:15:41+00:00: Loading Schedule
resque-scheduler: [INFO] 2016-09-22T22:15:41+00:00: Scheduling FixSchedulesJob
resque-scheduler: [INFO] 2016-09-22T22:15:41+00:00: Schedules Loaded
resque-scheduler: [INFO] 2016-09-22T22:16:11+00:00: queueing ScheduledTasks (FixSchedulesJob)
resque-scheduler: [INFO] 2016-09-22T22:16:41+00:00: queueing ScheduledTasks (FixSchedulesJob)
```

but the worker logs never change and I don't see `Running scheduled` in my server logs. Is there something else that needs to be done to connect the worker to the scheduler?

**Comment by carsonreinke** [comment]
Try this:

```
bundle exec rake resque:scheduler & 
env QUEUE=* bundle exec rake resque:work --trace &
```

It might just been the use of QUEUES=* instead of QUEUE=*, but not sure.

**Comment by carsonreinke** [comment]
@fergusom were you able to get that to work?

**Comment by fergusom** [comment]
using `QUEUE=*` started the worker ok, but now the scheduler isn't queueing any jobs. I just see:

```
resque-scheduler: [INFO] 2016-09-26T18:30:09+00:00: Starting
resque-scheduler: [INFO] 2016-09-26T18:30:09+00:00: Loading Schedule
resque-scheduler: [INFO] 2016-09-26T18:30:09+00:00: Scheduling FixSchedulesJob
resque-scheduler: [INFO] 2016-09-26T18:30:09+00:00: Schedules Loaded
```

and then it stops outputting any logs. I didn't change anything in my configuration or my YAML file. Do you know why the tasks would not be queued? Here is my YAML file again:

```
---
FixSchedulesJob:
  description: 'clear verification codes'
  queue: scheduled
  class: ScheduledTasks
  every: '30s'
```

**Comment by carsonreinke** [comment]
That is quite odd, especially since it said it was specifically scheduled.  Any chance you are loading two different schedules?  If you load resque-web, what does the Schedule tab say for that job?

**Comment by fergusom** [comment]
Must have been a temporary failure on my server because I just tried again and it started queueing tasks like before.

The worker still isn't processing the tasks however. I'm thinking now that maybe its running locally instead of on my server on heroku? I've been looking for a heroku specific command for this but haven't found anything yet.

**Comment by carsonreinke** [comment]
Maybe there is some info [here](https://devcenter.heroku.com/articles/queuing-ruby-resque#resque-on-heroku) that might help.

If you can resque worker locally, could you just run the resque-scheduler locally also?

**Comment by fergusom** [comment]
Thanks for the link I got it running on heroku with:

`TERM_CHILD=1 QUEUE=* heroku run rake resque:work --trace`

I see the worker starting in my server logs. However its still not running the tasks with the scheduler on the same server. I also tried with `QUEUES` and got the same result.

I can run both locally as well but the same thing happens: tasks are queued but never processed.

**Comment by carsonreinke** [comment]
Couple of things to check.  Is resque-scheduler outputting `queueing ScheduledTasks (FixSchedulesJob)` now and scheduling the job?  Do any jobs show in the queue within resque-web?  Do you have an initializer for resque/resque-scheduler?  If so, what are the contents?

It almost sounds like resque and resque-scheduler are using two separate Redis instances or DBs.  Is that possible with your setup?

**Comment by carsonreinke** [comment]
@fergusom Any luck on this?

**Comment by carsonreinke** [comment]
@fergusom were you able to get this to work?
