### ISSUE TITLE
how to remove a job in a particular queue? 

### ISSUE THREAD

**Issue by thomasjoyce** [resque/resque-scheduler#584]
hi,

   i did this to add a job in queue zzz:
 @job_request_enqueue = Resque.enqueue_at_with_queue('zzz', @job.start_datetime, ChannelEventsScheduler, @job.id)

how to remove the job in queue zzz?
i was expecting something like this:
@job_remove_in_enqueue = Resque.remove_delayed_with_queue ('zzz', ChannelEventsScheduler, @job.id)

But could not find a method like it. i did saw this ticket:
https://github.com/resque/resque-scheduler/pull/119

and idea if someone know what it is? thanks :p

**Comment by thomasjoyce** [comment]
never mind, i figure out the answer, directly remove it from redis instead.

Resque::Job.destroy('zzz', ChannelEventsScheduler, @job.id)

**Comment by carsonreinke** [comment]
If you want to remove an item from the delayed queue (not after queued to resque), see [`Resque.remove_delayed_selection`](https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/delaying_extensions.rb#L158)
