### ISSUE TITLE
How can dynamic assign other worker for pending job.

### ISSUE THREAD

**Issue by piyushawasthi** [resque/resque-scheduler#586]
I have a critial problem due to some issue there are 1200 jobs in a queue that queue assign an worker1 so how can I dynamic assign my free worker on the same queue to finish all pending jobs. is there any good solution for live server?

**Comment by carsonreinke** [comment]
This does not sound like it is related to resque-scheduler, but you could just start up a bunch of workers for the same queue (e.g. `bundle exec rake resque:work QUEUE=worker1`).  A queue can have multiple workers working on it.
