### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by lhf-leo** [resque/resque-scheduler#589]
Can resque-scheduler work with Rails 5? How to solve the gem dependency issue?

**Comment by lhf-leo** [comment]
> Bundler could not find compatible versions for gem "rack":
>   In Gemfile:
>     rails (= 5.0) was resolved to 5.0.0, which depends on
>       actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
>         rack (~> 2.0)
>     resque-scheduler was resolved to 4.3.0, which depends on
>       resque (~> 1.26) was resolved to 1.26.0, which depends on
>         sinatra (>= 0.9.2) was resolved to 1.1.0, which depends on
>           rack (~> 1.1)

**Comment by carsonreinke** [comment]
I had no issue with resque-scheduler 4.3.0 with rails 5.0.1.  What is the conflict you are receiving?

**Comment by lhf-leo** [comment]
@carsonreinke haven't worked on the project for a while, and the conflict seems already gone. I'm going to close this thread.
