### ISSUE TITLE
Race conditions with multiple schedulers

### ISSUE THREAD

**Issue by vipere** [resque/resque-scheduler#594]
The issue is with the detection of schedule changes, particularly the use of the redis key "schedules_changed".

- When a new scheduler is started, it loads the schedule from Redis, and deletes the "schedules_changed" key (in the load_schedule! method).
This should be done only by the master, otherwise we have no guarantee the master is aware of the change.
- When the master detects a schedule change, it removes the key from the "schedules_changed" hash in Redis. but we have no guarantee the other schedulers have detected that change as well.
Which means in case of failover to another scheduler, outdated schedules may be used.

**Comment by carsonreinke** [comment]
@vipere it sounds like a Redis channel is a better use for this instead of Redis key.  This was added in v2.0.0 of Redis, so support would be there.

**Comment by carsonreinke** [comment]
Looking at a quicker fix,

1. Deleting `schedules_changed` should only happen by the master
2. Since only the master uses `schedules_changed`, the slave will not use this
3. Fail over should have new master do a full schedule reload

**Comment by hlascelles** [comment]
I'm sure this is related to (but not the same as) another bug: https://github.com/resque/resque-scheduler/issues/419

Whatever solution is added can probably fix both issues.

**Comment by carsonreinke** [comment]
@hlascelles I don't really see how it is related, as https://github.com/resque/resque-scheduler/issues/419 is just about a prefix for the master lock.  Could you elaborate?

**Comment by hlascelles** [comment]
The master lock prefix allows two schedulers to share the same Redis namespace, but the `schedules_changed` doesn't use it. 

We are seeing two different services load a union of their schedules (as the use of the `schedules_changed` key is non-atomic and racey as you say), and thus workers from one service run jobs they don't know of from the other. 

If the master lock prefix was used, then at least that union issue would go away, but your racey problem would remain. So, similar problem space, slightly different symptoms.

**Comment by carsonreinke** [comment]
Correct, `schedules_changed` is not prefixed, since `RESQUE_SCHEDULER_MASTER_LOCK_PREFIX` is only for the master lock.  Having multiple schedulers with a prefix would not cause a race condition, since it would be different Redis keys.

**Comment by hlascelles** [comment]
It doesn't cause a race condition on the master lock, but it would contribute to the race condition on the `schedules_changed` value.

I suppose I am proposing that the `RESQUE_SCHEDULER_MASTER_LOCK_PREFIX` needs to become the `RESQUE_SCHEDULER_SERVICE_PREFIX` or similar.

**Comment by carsonreinke** [comment]
My bad, I see what you are saying now.  That would definitely cause an issue if you are using multiple master schedulers with a dynamic schedule.  Things would not go well at all.

I think what you are proposing makes sense, though I'm wondering if any other Redis keys need to be prefixed also.

**Comment by hlascelles** [comment]
Agreed... I can't comment there unfortunately, I don't know how many internal keys are used. I realise we are making (some) more trouble with ourselves by sharing a redis DB, but doing support with resque-web looking at one place is great.

**Comment by erickrom** [comment]
@carsonreinke about your quick fix, could we also somehow do a full schedule reload when a scheduler acquires the master lock?  That way whoever becomes the master scheduler gets the updated schedule.
