### ISSUE TITLE
Job doesn't run from static schedule

### ISSUE THREAD

**Issue by Babdus** [resque/resque-scheduler#613]
Hello,
I have read similar issues but nothing helped me.

Here is my lib/tasks/resque.rake file:
```
require 'resque/tasks'
require 'resque/scheduler/tasks'

namespace :resque do
  task :setup do
    require 'resque'
    require 'resque-scheduler'
  end
  task :setup_schedule => :setup do
    require 'resque-scheduler'
    Resque.schedule = YAML.load_file("#{Rails.root}/config/resque_schedule.yml")
  end
  task :scheduler => :setup_schedule
end
```
And resque_schedule.yml:
```
TestCronJob:
  every: '1m'
  class: TestCronJob
  queue: test
  description: "This job puts something every 1 minute"
```
And this is test_cron_job.rb:
```
class TestCronJob < ApplicationJob
  queue_as :test

  def perform
    puts 'something'
  end

end
```
In command line:
```
QUEUE=* bundle exec rake environment resque:work&
```
and
```
rake environment resque:scheduler
```
The job is being queued, but never run (I tested on several jobs, not just putting something):
```
resque-scheduler: [INFO] 2017-05-29T02:36:07+04:00: Starting
resque-scheduler: [INFO] 2017-05-29T02:36:07+04:00: Loading Schedule
resque-scheduler: [INFO] 2017-05-29T02:36:07+04:00: Scheduling TestCronJob 
resque-scheduler: [INFO] 2017-05-29T02:36:07+04:00: Schedules Loaded
resque-scheduler: [INFO] 2017-05-29T02:37:07+04:00: queueing TestCronJob (TestCronJob)
resque-scheduler: [INFO] 2017-05-29T02:38:07+04:00: queueing TestCronJob (TestCronJob)
```
Can anybody help me find out what is going wrong?

**Comment by carsonreinke** [comment]
@Babdus You will need to actually run a resque worker like `bundle exec rake resque:work QUEUE=*`.  resque-scheduler just simply queues the job.

**Comment by carsonreinke** [comment]
@Babdus Any chance this is using a different Redis instance or database?  Could you try running `resque:work` with the `VERBOSE=1`

**Comment by Babdus** [comment]
I have only one Redis instance with one database, so it can't be the case.
After running `resque:work` with the `VERBOSE=1` here is the output:
```
*** Starting worker main
*** Running before_first_fork hooks
*** got: (Job{test} | TestCronJob | [])
*** Running before_fork hooks with [(Job{test} | TestCronJob | [])]
*** Running after_fork hooks with [(Job{test} | TestCronJob | [])]
*** done: (Job{test} | TestCronJob | [])
```
But nothing ever happened. (I've put code in this TestCronJob for retrying failed jobs)

**Comment by carsonreinke** [comment]
This issue is unrelated to resque-scheduler, as clearly the job is being queued into the right place and resque is running it.

With that said, I think your problem is `ApplicationJob` defines `self.perform`, but in your `TestCronJob` that defines the instance method `perform`, not the class level, so try changing that to just `def self.perform` and it should work.

**Comment by sevos** [comment]
I have the same issue. It seems that resque-schedule does not play with ActiveJob adapter. When I enqueue job manually, I get the following output:

```
*** got: (Job{default} | ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper | [{"job_class"=>"BrainTickJob", "job_id"=>"a4abb078-fc2e-4ce9-bdd0-d781861d0815", "queue_name"=>"default", "priority"=>nil, "arguments"=>[], "executions"=>0, "locale"=>"en"}])
```

vs resque-schedule from static schedule:

```
*** got: (Job{default} | BrainTickJob | [])
```

**Comment by canted** [comment]
I'm seeing the same issue.  I did get it to work with these settings, as an ugly workaround

```
job = HelloJob.new
Resque.schedule = {
  hello: {
    every: "10s",
    class: "ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper",
    queue: :default,
    args: {"job_class"=>job.class.to_s, "job_id"=>job.job_id, "queue_name"=>job.queue_name, "priority"=>nil, "arguments"=>[], "locale"=>"en"},
    description: "Hello World"
  },
}
```

**Comment by carsonreinke** [comment]
@sevos Any chance you can run that with the `VERBOSE` on?  There should be no reason why either should not work.

**Comment by TimFletcher** [comment]
I was having the exact same problem as @sevos and @Babdus. Using the following worked for me:

```
CopyClickStatsJob:
  every: '10s'
  class: ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
  queue: default
  description: "Migrate click stats from the write table to the read table"
  args:
    job_class:  CopyClickStatsJob
    queue_name: default
    arguments: []
```

**Comment by MickaelMagniez** [comment]
@TimFletcher solution work for me too

**Comment by glebm** [comment]
resque-scheduler still doesn't work with ActiveJob out of the box (despite the issue being closed). Is there anything that can be done here to make them compatible?

Resque itself does work with ActiveJob out of the box (except `queue_from_class` doesn't work).

**Comment by jpcuevaslavin** [comment]
@TimFletcher solution worked for me too. Thanks!

**Comment by stuartluscombe** [comment]
The solution from @TimFletcher worked for me also.

I tried the active-scheduler gem but I ran in to issues with resque-scheduler not initialising correctly.

**Comment by MartinSugasti** [comment]
@TimFletcher your code worked for me. Thanks.

**Comment by justrenato** [comment]
@TimFletcher worked for me too. Cant believe that's still happenning ;-;

**Comment by jronallo** [comment]
If instead of a scheduled job you're using `enqueue_at_with_queue` you can do something like this which includes arguments:

```ruby
time_to_send = Time.now + 120
Resque.enqueue_at_with_queue(
        :mail_updates,
       time_to_send,
        ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper,
        {
          job_class: SubscriptionsJob,
          job_id: SecureRandom.uuid,
          queue_name: :mail_updates,
          priority: nil,
          arguments: [{arg1: "value", another_arg: "value2"}],
          locale: 'en'
        }
      )
```

**Comment by mingan** [comment]
Another option is to use the mechanism for [custom-jobs](https://github.com/resque/resque-scheduler?tab=readme-ov-file#support-for-resque-status-and-other-custom-jobs) by defining `::scheduled` in the job class (or `ApplicationJob`) that will let ActiveJob do the enqueuing and thus adding the adapter and metadata (`executions`, `enqueued_at`, ...) that might be useful (e.g. for queued time metric).

```ruby
  def self.scheduled(_queue, _klass, *args)
    self.perform_later *args
  end
```

This can be used with basic schedule definition:

```yaml
job_name:
   every: 10m
   class: MyJob
```

I've found it when trying to pass current time as a job argument when enqueuing.
