### ISSUE TITLE
resque-scheduler silently dying

### ISSUE THREAD

**Issue by magandrez** [resque/resque-scheduler#621]
Hi,

So, I have couple of instances running resque. In one of them I have a master and the scheduler running and several workers. The other instance runs only workers.

To start the process, I use capistrano like below

```  task :start_scheduler  do
    puts "*** \033[1;42m Starting Resque scheduler...\033[0m"
    cmd = "cd #{current_path}; " +
          "if [ -f tmp/pids/scheduler.pid ]; " +
          "then echo \"*** \033[1;101;93m Cannot start 2 schedulers. " +
            "Kill old one first. ***\033[0m\"; " +
          "else BACKGROUND=yes VERBOSE=1 PIDFILE=tmp/pids/scheduler.pid "+
            "nohup bundle exec rake resque:scheduler " +
            ">>#{shared_path}/log/resque-scheduler.log 2>&1; fi"
    run cmd
  end
```
The above starts a scheduler in the master instance (Capistrano takes care of this).

The problem I have is that every 7 days, the scheduler silently dies (not able to find it in the process list in the machine), there is no trace in any log of the process dying. I know the description is a little vague, and might not be related to resque-scheduler, but I would like to find validation. 

Out of the scope is Linux OOM killing the process. The instance has plenty of free memory, and in any case it would randomly select a process to be killed, not always the same process, if I understood OOM correctly.

**Comment by chrisinmtown** [comment]
The resque-scheduler plugin logs details to files like resque-scheduler-YYYY-MM-DD.log and resque-scheduler-error.log. Can you post the contents of those files from about the time when it stopped? Does it reliably die every 7 days? 

We have seen the resque-scheduler exit without warning but not on a neat pattern like exactly every 7 days.  We are watching for it to happen again and will gather information then.

**Comment by magandrez** [comment]
Hi @chrisinmtown, 

Unfortunately, I don't have access to the environment related to the original issue above described.

Feel free to close the issue.

Thanks for showing interest on taking a look at it though.
