### ISSUE TITLE
tzdata-2017c-1.el6.noarch centos-6.9

### ISSUE THREAD

**Issue by mitchellthompson** [resque/resque-scheduler#623]
Resque scheduler is producing the following error after upgrading to tzdata-2017c-1.el6.noarch in centos 6.9:

TZInfo::InvalidTimezoneIdentifier: The file '/usr/share/zoneinfo/leapseconds' does not start with the expected header.

Full stack trace:

TZInfo::InvalidTimezoneIdentifier: The file '/usr/share/zoneinfo/leapseconds' does not start with the expected header.
/applications/mobi/shared/bundle/ruby/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_data_source.rb:205:in `rescue in load_timezone_info'
/applications/mobi/shared/bundle/ruby/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_data_source.rb:202:in `load_timezone_info'
/applications/mobi/shared/bundle/ruby/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:92:in `get'
/applications/mobi/shared/bundle/ruby/gems/tzinfo-1.2.3/lib/tzinfo/timezone_proxy.rb:96:in `real_timezone'
/applications/mobi/shared/bundle/ruby/gems/tzinfo-1.2.3/lib/tzinfo/timezone_proxy.rb:30:in `period_for_utc'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/zotime.rb:316:in `block in get_tzone'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/zotime.rb:315:in `each'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/zotime.rb:315:in `find'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/zotime.rb:315:in `get_tzone'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/cronline.rb:61:in `initialize'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/jobs.rb:632:in `new'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler/jobs.rb:632:in `initialize'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler.rb:639:in `new'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler.rb:639:in `do_schedule'
/applications/mobi/shared/bundle/ruby/gems/rufus-scheduler-3.3.1/lib/rufus/scheduler.rb:245:in `cron'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:143:in `block in load_schedule_job'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:138:in `each'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:138:in `load_schedule_job'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:100:in `block in load_schedule!'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:99:in `each'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:99:in `load_schedule!'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:302:in `reload_schedule!'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler.rb:50:in `run'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler/cli.rb:117:in `run_forever'
/applications/mobi/shared/bundle/ruby/gems/resque-scheduler-4.3.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <top (required)>'
/applications/mobi/shared/bundle/ruby/gems/airbrake-6.1.1/lib/airbrake/rake.rb:19:in `execute'
/applications/mobi/shared/bundle/ruby/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/mobi/.gem/ruby/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/applications/mobi/current/bin/bundle:3:in `load'
/applications/mobi/current/bin/bundle:3:in `<main>'

Temporary work around for the issue:
yum downgrade tzdate

Please let me know if this should be submitted on the centos bugs instead.

Thanks!

**Comment by carsonreinke** [comment]
@mitchellthompson This is actually related to the gem [tzinfo](https://rubygems.org/gems/tzinfo), but thank you for reporting.
