### ISSUE TITLE
Push new release v4.3.1

### ISSUE THREAD

**Issue by carsonreinke** [resque/resque-scheduler#626]
I do not have access to push this gem, please push it or add access for me `gem owner resque-scheduler --add carson@reinke.co` @meatballhat

**Comment by carsonreinke** [comment]
@bvandenbos @sirupsen @yaauie Any help?

**Comment by sirupsen** [comment]
```
Owner added successfully.
Owners for gem: resque-scheduler
- carson@reinke.co
- sirup@sirupsen.com
- ryan@yaauie.com
- bvandenbos@gmail.com
- dan@meatballhat.com
```

**Comment by meatballhat** [comment]
@carsonreinke Sorry, I just saw this!  Thanks much, @sirupsen :heart: :100:

**Comment by carsonreinke** [comment]
Thanks!!!
