### ISSUE TITLE
4.3.1 release not tagged / no changelog update

### ISSUE THREAD

**Issue by bgeuken** [resque/resque-scheduler#628]
Hi guys,

I just noticed that there was a new [release](https://rubygems.org/gems/resque-scheduler/versions/4.3.1), but there is no entry in the changelog about it. Also there is no tagged commit.

Seems like this was forgotten:-)

**Comment by carsonreinke** [comment]
@bgeuken Not sure how something this simple got away from me, oddly put in https://github.com/resque/resque-scheduler/pull/634, this can't happen again.
