### ISSUE TITLE
2.0.0.b produces NoMethodError on start when resque_schedule.yml is empty

### ISSUE THREAD

**Issue by readbeam** [resque/resque-scheduler#64]
/home/me/.rvm/gems/ruby-1.9.2-p180/gems/resque-scheduler-2.0.0.b/lib/resque_scheduler.rb:32:in 'schedule=': undefined method 'each' for false:FalseClass (NoMethodError)

**Comment by chrishough** [comment]
I am getting a similar error here: https://github.com/resque/resque-scheduler/issues/581
