### ISSUE TITLE
Make it run faster!

### ISSUE THREAD

**Issue by dimasusername** [resque/resque-scheduler#640]
So in production when we dynamically queue specific jobs there may be a significant job count for each timestamp, i.e. >300. And what I noticed is that often the scheduler begins to lag - queuing tasks that were supposed to be queued 20 minutes ago.

We run it on a very high spec server yet it uses very few resources.

I couldn't find any option except for RESQUE_SCHEDULER_INTERVAL to control the scheduler performance and somehow make it use more of the resources available to process more items faster.

**Comment by jeremy** [comment]
Faster would be better! However, 20 min to enqueue ~hundreds of jobs suggests that you're hitting a timeout or something. Run with VERBOSE set to troubleshoot. 👍

**Comment by dimasusername** [comment]
@jeremy no timeouts, it's just not keeping up with the dynamic schedule. Is there any configuration that might make it use more of the available resources, or perhaps run several scheduler processes together?
