### ISSUE TITLE
resque-scheduler does not seem to observe the return value of the before_schedule hook 

### ISSUE THREAD

**Issue by jurisgalang** [resque/resque-scheduler#650]
What I'm observing:

I've got a resque-schedule.yml set to execute/enqueue a job every hour on the hour.
And the job class implements a `before_schedule` hook:
```ruby
def self.before_schedule_check_if_enabled(*_)
  false
end
```
But I'm still seeing the job enqueued and performed every hour on the hour.

Could this be related to the issue addressed by: https://github.com/resque/resque-scheduler/pull/616?

**Comment by jeremy** [comment]
Fix @ #679
