### ISSUE TITLE
Undocumented "requeue with params" feature

### ISSUE THREAD

**Issue by mchwalek** [resque/resque-scheduler#651]
Hi. I was looking through the code when I noticed the following https://github.com/resque/resque-scheduler/blob/78c5325e91a8588344e64379021afc7812f7f4bb/lib/resque/scheduler/server.rb#L48
It looks like there's an undocumented feature, that's triggered when scheduled job contains `params` key in its config.

Why is this undocumented? Is it not "production ready" due to some major problem? Are there plans to officially "release" this feature?

**Comment by rafaelfranca** [comment]
It seems it is just undocumented because nobody did add the documentation yet. Do you mind to open a PR?

**Comment by iloveitaly** [comment]
@mchwalek friendly ping here to open up a PR with documentation for this!

**Comment by mchwalek** [comment]
@iloveitaly Hi, sorry for the long delay. I opened a PR for this https://github.com/resque/resque-scheduler/pull/749

**Comment by mchwalek** [comment]
@iloveitaly Thanks for the merge. Can you close the issue?
