### ISSUE TITLE
Redis Keyspace Scanning Entire Question

### ISSUE THREAD

**Issue by tmedford** [resque/resque-scheduler#658]
"It is recommended that a production deployment of resque-scheduler be hosted on a dedicated Redis database. While making and managing scheduled tasks, resque-scheduler currently scans the entire Redis keyspace, which may cause latency and stability issues if resque-scheduler is hosted on a Redis instance storing a large number of keys (such as those written by a different system hosted on the same Redis instance)" 

Can you please refer to the section of code that does this? Would it be advised to keep session storage in one redis database and queuing jobs in another on the same redis instance?

**Comment by rafaelfranca** [comment]
It is here https://github.com/resque/resque-scheduler/blob/78c5325e91a8588344e64379021afc7812f7f4bb/lib/resque/scheduler/delaying_extensions.rb#L188-L211.

I'd not mix session storage and queuing job in the same redis stance. They have different resiliency requirements.
