### ISSUE TITLE
'Clear Delayed Jobs' is a bad idea

### ISSUE THREAD

**Issue by sjernigan** [resque/resque-scheduler#659]
We depend on a reliable method for scheduling future jobs.  Many of our jobs are scheduled way into the future so our delayed queue can be very long.  Having a button for clearing the delayed jobs with no protection around to prevent accidental use is a horrible idea.  Locating it adjacent to the "Next" paging links is almost negligent. There should be a configuration option for hiding this button altogether.  Someday over a beer I'll tell you about how security scanning software found this button and poked it for us.

**Comment by rafaelfranca** [comment]
Agree. Mind to open a PR?

**Comment by mishina2228** [comment]
I created #754 for this issue.
