### ISSUE TITLE
v4.4.0 bug: Publish new version with 'require redis/errors' fix 

### ISSUE THREAD

**Issue by jesperronn** [resque/resque-scheduler#675]
As the fix in https://github.com/resque/resque-scheduler/pull/671 is merged onto master, it will make sense to make a new release, semantically versioned as a patch release for v4.4.0, since it fixes a bug in v4.4.0

Although I wrote this in the merged PR #671, I am creating this as a separate issue for you maintainers to keep track of.

* [ ] Release patch for v4.4.0 containing PR #671

Once again, thanks for your work of maintaining this library. Open source maintentance sometimes is hard, boring, and perhaps even unrelated, as maintainers often move forward to other projects. Thanks for your work!

**Comment by ikhurramraza** [comment]
Any news on when will this be released?

**Comment by eriko-de** [comment]
Any news? #Push

**Comment by iloveitaly** [comment]
New release is cut! https://github.com/resque/resque-scheduler/releases/tag/v4.5.0
