### ISSUE TITLE
Schedule hooks do not behave as expected or documented

### ISSUE THREAD

**Issue by jweir** [resque/resque-scheduler#679]
https://github.com/resque/resque-scheduler#hooks

My reading of the `before_schedule` and `after_schedule` hooks is they should be called around when job is about to be put on the queue via `enqueue_from_config`.

However the `{before,after}_schedule` methods are only called when a job is enqueued via `enqueue_at`, `enqueue_in`, or `enqueue_at_with_queue`.

This could be my misreading of the documentation, in which case the documentation could be cleared up.  But it seems that a callback called `before_schedule` would be associated with a `cron` schedule job.

See also #650

**Comment by jeremy** [comment]
PR with fix @ #681
