### ISSUE TITLE
Any plan to cut a new version?

### ISSUE THREAD

**Issue by shicholas** [resque/resque-scheduler#699]
Our team has had static code analysis done and it's found the `master` version is more safe than the last published one. We've noticed that the last version has been published over a year ago - do you have any plans to cut a version, or are there remaining tasks that we can help with in order to do so?

Thank you,

**Comment by michaelglass** [comment]
FWIW, we've been using a newer version than 4.4.0 for a while now because of a bunch of bug fixes that have landed in master.
