### ISSUE TITLE
need for new collaborators?

### ISSUE THREAD

**Issue by michaelglass** [resque/resque-scheduler#705]
Howdy folks!

There are a bunch of changes in master that haven't made it out in a new release, (e.g. #675, #699). I'm happy to help do a little maintenance.

(thank you for your hard work so far)

**Comment by iloveitaly** [comment]
New release is cut! https://github.com/resque/resque-scheduler/releases/tag/v4.5.0

Would love help with any of the open PRs with comments, or other changes you'd like to see.
