### ISSUE TITLE
Dalayed Job page is not loading in. rails 6 and ruby 3

### ISSUE THREAD

**Issue by shodhangk** [resque/resque-scheduler#712]
Hi,

When I tried to view the list of delayed jobs in the UI it is failing with the below error.

```
 NoMethodError - undefined method `escape' for URI:Module:
	/Users/shodhangk/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/resque-scheduler-4.4.0/lib/resque/scheduler/server.rb:132:in 
```

In ruby 3, the `escape` method is removed for URI. So alternative method need to be used.

**Comment by YoogoC** [comment]
#709

**Comment by sharang-d** [comment]
Could someone release a new version, please?

**Comment by iloveitaly** [comment]
@sharang-d there's a couple things we need to do before a new release. Here's a list of you want to chip in with PRs:

https://github.com/resque/resque-scheduler/pull/671#issuecomment-924974183

**Comment by iloveitaly** [comment]
This has been fixed https://github.com/resque/resque-scheduler/releases/tag/v4.5.0
