### ISSUE TITLE
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

### ISSUE THREAD

**Issue by seb-sykio** [resque/resque-scheduler#745]
I have this deprecation with Resque.remove_delayed

`    Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

 Redis::Namespace.pipelined(&block#Proc) at .rvm/gems/ruby-3.1.1/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:301
    Resque::DataStore.method_missing(sym#Symbol, *args#Array, &block#Proc) at .rvm/gems/ruby-3.1.1/gems/resque-2.2.1/lib/resque/data_store.rb:65
    Resque::Scheduler::DelayingExtensions.remove_delayed_job(encoded_job#String) at .rvm/gems/ruby-3.1.1/gems/resque-scheduler-4.5.0/lib/resque/scheduler/delaying_extensions.rb:302
    Resque::Scheduler::DelayingExtensions.remove_delayed(klass#Class, *args#Array) at .rvm/gems/ruby-3.1.1/gems/resque-scheduler-4.5.0/lib/resque/scheduler/delaying_extensions.rb:150`

**Comment by cody-elhard** [comment]
This is already in the master branch

https://github.com/resque/resque-scheduler/commit/cb3e9f6aa6b520609a8c223a7e11f31f6c2c361c

**Comment by codealchemy** [comment]
It looks like [deprecation warnings are still happening in CI](https://github.com/resque/resque-scheduler/runs/5711844338?check_suite_focus=true) on the latest `master` (though not related to this gem, those warnings are coming from dependencies - see https://github.com/resque/redis-namespace/issues/193 / https://github.com/resque/resque/issues/1794)

**Comment by chinyakao** [comment]
Hi,
When I was doing scheduler job, it is still happening.
Could anyone help me figure out?

```
# config/schedule.yml

send_reminder:
  cron: "*/5 * * * *"
  class: "SendReminder"
  queue: high
  args:
  description: "This job queues all content for indexing in solr"
```

**Comment by chinyakao** [comment]
@mishina2228 Thank you so much!

**Comment by mishina2228** [comment]
@seb-sykio (Cc: @PatrickTulskie, @iloveitaly)
resque [v2.3.0](https://github.com/resque/resque/releases/tag/v2.3.0) (the latest is [v2.4.0](https://github.com/resque/resque/releases/tag/v2.4.0)) and resque-scheduler [v4.6.0](https://github.com/resque/resque-scheduler/releases/tag/v4.6.0), which address this issue, has already been released.
So I believe we can close this issue.

**Comment by PatrickTulskie** [comment]
@mishina2228 Got it. Closing this out. Thanks!
