### ISSUE TITLE
Error requiring resque/scheduler/tasks file

### ISSUE THREAD

**Issue by ZeroFries** [resque/resque-scheduler#751]
After upgrading ruby to 3.1.2, I'm getting the following error on resque-scheduler 2.5.1:

`require': cannot load such file -- resque/scheduler/tasks

I've tried uninstalling and re-installing resque and resque/scheduler, still getting the same error.

**Comment by DanBenHa** [comment]
Do you mind sharing the solution? I get the same error in 4.10.0
