### ISSUE TITLE
Dynamic schedule, resque-web and class queue name.

### ISSUE THREAD

**Issue by sreid99** [resque/resque-scheduler#78]
If I use set_schedule to create a job, I get an error in resque-web unless if I specify a queue name in the set_schedule argument.  I thought this field was optional, and it would otherwise use the queue name in the class which has the perform method.

The job does actually run, but when I try to view the schedule page in resque-web, I get the following:

NameError at /schedule
uninitialized constant MyClass

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/lib/resque/helpers.rb in const_get

```
constant = constant.const_get(name) || constant.const_missing(name)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/lib/resque/helpers.rb in constantize

```
constant = constant.const_get(name) || constant.const_missing(name)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/lib/resque/helpers.rb in each

```
names.each do |name|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/lib/resque/helpers.rb in constantize

```
names.each do |name|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-scheduler-2.0.0.d/lib/resque_scheduler/server.rb in queue_from_class_name

```
Resque.queue_from_class(Resque.constantize(class_name))
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-scheduler-2.0.0.d/lib/resque_scheduler/server.rb in each

```
end
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-scheduler-2.0.0.d/lib/resque_scheduler/server.rb in evaluate_source

```
end
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/tilt-1.3/lib/tilt/template.rb in cached_evaluate

```
evaluate_source(scope, locals, &block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/tilt-1.3/lib/tilt/template.rb in evaluate

```
cached_evaluate(scope, locals, &block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/tilt-1.3/lib/tilt/template.rb in render

```
evaluate scope, locals || {}, &block
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in render

```
output = template.render(scope, locals, &block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in erb

```
render :erb, template, options, locals
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-scheduler-2.0.0.d/lib/resque_scheduler/server.rb in GET /schedule

```
erb File.read(File.join(File.dirname(__FILE__), 'server/views/scheduler.erb'))
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call

```
proc { unbound_method.bind(self).call(*@block_params) } :
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in compile!

```
proc { unbound_method.bind(self).call(*@block_params) } :
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in instance_eval

```
throw :halt, instance_eval(&block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in route_eval

```
throw :halt, instance_eval(&block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in route!

```
route_eval(&block)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in process_route

```
yield
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in catch

```
catch(:pass) do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in process_route

```
catch(:pass) do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in route!

```
pass_block = process_route(pattern, keys, conditions) do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in each

```
routes.each do |pattern, keys, conditions, block|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in route!

```
routes.each do |pattern, keys, conditions, block|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in dispatch!

```
route!
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call!

```
invoke { dispatch! }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in instance_eval

```
res = catch(:halt) { instance_eval(&block) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in invoke

```
res = catch(:halt) { instance_eval(&block) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in catch

```
res = catch(:halt) { instance_eval(&block) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in invoke

```
res = catch(:halt) { instance_eval(&block) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call!

```
invoke { dispatch! }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call

```
dup.call!(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/rack-1.2.2/lib/rack/head.rb in call

```
status, headers, body = @app.call(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/showexceptions.rb in call

```
@app.call(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call

```
synchronize { prototype.call(env) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in synchronize

```
yield
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb in call

```
synchronize { prototype.call(env) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/rack-1.2.2/lib/rack/content_length.rb in call

```
status, headers, body = @app.call(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/rack-1.2.2/lib/rack/chunked.rb in call

```
status, headers, body = @app.call(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/rack-1.2.2/lib/rack/handler/mongrel.rb in process

```
status, headers, body = @app.call(env)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in process_client

```
handler.process(request, response)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in each

```
handlers.each do |handler|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in process_client

```
handlers.each do |handler|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in run

```
thread = Thread.new(client) {|c| process_client(c) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in initialize

```
thread = Thread.new(client) {|c| process_client(c) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in new

```
thread = Thread.new(client) {|c| process_client(c) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in run

```
thread = Thread.new(client) {|c| process_client(c) }
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in initialize

```
@acceptor = Thread.new do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in new

```
@acceptor = Thread.new do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb in run

```
@acceptor = Thread.new do
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/rack-1.2.2/lib/rack/handler/mongrel.rb in run

```
server.run.join
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/vegas-0.1.8/lib/vegas/runner.rb in run!

```
rack_handler.run app, :Host => host, :Port => port do |server|
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/vegas-0.1.8/lib/vegas/runner.rb in start

```
run!
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/vegas-0.1.8/lib/vegas/runner.rb in initialize

```
start(path)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/bin/resque-web in new

```
Vegas::Runner.new(Resque::Server, 'resque-web', {
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/gems/resque-1.15.0/bin/resque-web in nil

```
Vegas::Runner.new(Resque::Server, 'resque-web', {
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/bin/resque-web in load

```
load Gem.bin_path('resque', 'resque-web', version)
```

C:/RailsInstaller/Ruby1.8.7/lib/ruby/gems/1.8/bin/resque-web in nil

```
load Gem.bin_path('resque', 'resque-web', version)
```

**Comment by sahanmalagi** [comment]
It would be nice to add some validation to resque web. I am also experiencing this problem
